export default {
  computed: {
    colors () {
      return [
        { label: 'success', value: 'success' },
        { label: 'important', value: 'important' },
        { label: 'critical', value: 'critical' },
        { label: 'informational', value: 'informational' },
        { label: 'inactive', value: 'inactive' },
        { label: 'Ruby', value: 'cc342d' },
        { label: 'Ruby on Rails', value: 'cc0000' },
        { label: 'PHP', value: '8892be' },
        { label: 'Docker', value: '2d8dec' },
        { label: 'Node.js', value: '68a84e' },
        { label: 'Go', value: '159bce' },
        { label: 'MySQL', value: 'f29221' },
        { label: 'Vue.js', value: '4fc08d' },
        { label: 'HTML5', value: 'f06529' },
        { label: 'Laravel', value: 'ff2d20' },
        { label: 'React', value: '53d2f9' },
        { label: 'RaspberryPi', value: 'b5003a' },
        { label: 'Heroku', value: '79589f' },
        { label: 'Vim', value: 'red' },
        { label: 'Kotlin', value: 'red' },
        { label: 'WordPress', value: 'red' },
        { label: 'kubernetes', value: 'red' },
        { label: 'Azure', value: 'red' },
        { label: 'Firebase', value: 'red' },
        { label: 'PostgreSQL', value: 'red' },
        { label: 'lambda', value: 'red' },
        { label: 'TensorFlow', value: 'red' },
        { label: 'nginx', value: '128d00' },
        { label: 'Scala', value: 'red' },
        { label: 'Apache', value: 'red' },
        { label: 'ShellScript', value: 'red' },
        { label: 'Angular', value: 'blue' },
        { label: 'Django', value: '0e3c27' },
        { label: 'Flask', value: 'red' },
        { label: 'CakePHP', value: 'red' },
        { label: 'red', value: 'red' },
        { label: 'blue', value: 'blue' },
        { label: 'green', value: 'green' },
        { label: 'yellow', value: 'yellow' },
      ]
    }
  }
}