export default {
  computed: {
    types () {
      return [
        { label: 'Plastic', value: 'plastic' },
        { label: 'Flat', value: 'flat' },
        { label: 'Square', value: 'flat-square' },
        { label: 'For the Badge', value: 'for-the-badge' },
      ]
    },
    defaultColors () {
      return [
        { label: 'Success', color: '#44cc11' },
        { label: 'Important', color: '#fe7d37' },
        { label: 'Critical', color: '#e05d44' },
        { label: 'Information', color: '#007ec6' },
        { label: 'Inactive', color: '#9f9f9f' },
      ]
    },
    presetColors () {
      return [
        { label: 'Ruby', color: '#cc0000', icon: 'ruby' },
        { label: 'PHP', color: '#8892be', icon: 'php' },
        { label: 'Laravel', color: '#ff2d20', icon: 'laravel' },
        { label: 'Vue.js', color: '#4fc08d', icon: 'vue.js' },
        { label: 'Docker', color: '#53d2f9', icon: 'docker' },
        { label: 'Heroku', color: '#79589f', icon: 'heroku' },
      ]
    },
    icons () {
      return [
        { label: '---', value: null },
        { label: 'AngularJS', value: 'angularjs' },
        { label: 'Apache', value: 'apache' },
        { label: 'AppVeyor', value: 'appveyor' },
        { label: 'Atom', value: 'atom' },
        { label: 'Babel', value: 'babel' },
        { label: 'Bootstrap', value: 'bootstrap' },
        { label: 'Bulma', value: 'bulma' },
        { label: 'CakePHP', value: 'cakephp' },
        { label: 'CentOS', value: 'centos' },
        { label: 'CircleCI', value: 'circleci' },
        { label: 'CoffeeScript', value: 'coffeescript' },
        { label: 'Composer', value: 'composer' },
        { label: 'Docker', value: 'docker' },
        { label: 'CSS3', value: 'css3' },
        { label: 'curl', value: 'curl' },
        { label: 'C#', value: 'c-sharp' },
        // { label: 'C++', value: 'cplus-plus' },
        { label: 'ESLint', value: 'eslint' },
        { label: 'Firebase', value: 'firebase' },
        { label: 'Flask', value: 'flask' },
        { label: 'Flutter', value: 'flutter' },
        { label: 'Font Awesome', value: 'font-awesome' },
        { label: 'FreeBSD', value: 'freebsd' },
        { label: 'Gatsby', value: 'gatsby' },
        { label: 'Git', value: 'git' },
        { label: 'GitHub', value: 'github' },
        { label: 'Go', value: 'go' },
        { label: 'Grafana', value: 'grafana' },
        { label: 'GraphQL', value: 'graphql' },
        { label: 'Heroku', value: 'heroku' },
        { label: 'HTML5', value: 'html5' },
        { label: 'Java', value: 'java' },
        { label: 'JavaScript', value: 'javascript' },
        { label: 'Jekyll', value: 'jekyll' },
        { label: 'Jenkins', value: 'jenkins' },
        { label: 'jQuery', value: 'jquery' },
        { label: 'JSON', value: 'json' },
        { label: 'Kibana', value: 'kibana' },
        { label: 'Kotlin', value: 'kotlin' },
        { label: 'Kubernetes', value: 'kubernetes' },
        { label: 'Laravel', value: 'laravel' },
        { label: 'Linux', value: 'linux' },
        { label: 'Lua', value: 'lua' },
        { label: 'Lumen', value: 'lumen' },
        { label: 'MariaDB', value: 'mariadb' },
        { label: 'Material Design', value: 'material-design' },
        { label: 'MongoDB', value: 'mongodb' },
        { label: 'Netlify', value: 'netlify' },
        { label: 'NGINX', value: 'nginx' },
        { label: 'Node.js', value: 'node.js' },
        { label: 'Nodemon', value: 'nodemon' },
        { label: 'Nuxt.js', value: 'nuxt.js' },
        { label: 'OCaml', value: 'ocaml' },
        { label: 'OpenBSD', value: 'openbsd' },
        { label: 'Perl', value: 'perl' },
        { label: 'PHP', value: 'php' },
        { label: 'PostgreSQL', value: 'postgresql' },
        { label: 'Python', value: 'python' },
        { label: 'Raspberry Pi', value: 'raspberry-pi' },
        { label: 'React', value: 'react' },
        { label: 'Red Hat', value: 'red-hat' },
        { label: 'Redis', value: 'redis' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'RubyGems', value: 'rubygems' },
        { label: 'Ruby on Rails', value: 'rails' },
        { label: 'Rust', value: 'rust' },
        { label: 'Hugo', value: 'hugo' },
        { label: 'Scala', value: 'scala' },
        { label: 'Spring', value: 'spring' },
        { label: 'SQLite', value: 'sqlite' },
        { label: 'Storybook', value: 'storybook' },
        { label: 'Swift', value: 'swift' },
        { label: 'Symfony', value: 'symfony' },
        { label: 'TensorFlow', value: 'tensorflow' },
        { label: 'Terraform', value: 'terraform' },
        { label: 'Travis CI', value: 'travis-ci' },
        { label: 'TypeScript', value: 'typescript' },
        { label: 'Ubuntu', value: 'ubuntu' },
        { label: 'Unity', value: 'unity' },
        { label: 'Vim', value: 'vim' },
        { label: 'Visual Studio Code', value: 'visual-studio-code' },
        { label: 'Vue.js', value: 'vue.js' },
        { label: 'Webpack', value: 'webpack' },
        { label: 'WordPress', value: 'wordpress' },
        { label: 'Yarn', value: 'yarn' },
        { label: 'Zend Framework', value: 'zend-framework' }
      ]
    }
  }
}